language: java
# skip installation step

install: true	

script:
- mvn -f MMU_UniversityManager/pom.xml clean verify -Pjacoco-report coveralls:report

cache:
directories:
- $HOME/.m2

jdk:
- oraclejdk8
- oraclejdk7
- openjdk8
