language: java
# skip installation step

install: true

cache:
directories:
- $HOME/.m2

matrix:
fast_finish: true
include:
- jdk: oraclejdk8
env: WITH_COVERALLS=true
- jdk: oraclejdk7
env: WITH_COVERALLS=false
- jdk: openjdk6

jdk:
- oraclejdk8
- oraclejdk7
- openjdk8

script:
- if ["$WITH_COVERALLS" == "true" ];
then 
mvn -f MMU_UniversityManager/pom.xml clean verify -Pjacoco-report coveralls:report;
else
mvn -f MMU_UniversityManager/pom.xml clean verify;
fi
