language: java
# skip installation step
install: true

cache:
directories:
- $HOME/.m2

script:
 - mvn -f MMU_UniversityManager/pom.xml clean verify -Pjacoco-report coveralls:report;

matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode8
    - jdk: oraclejdk8
