language: java
# skip installation step

install: true	

script:
- mvn -f MMU_UniversityManager/pom.xml clean verify -Pjacoco-report coveralls:report

cache:
directories:
- $HOME/.m2

jdk:
- oraclejdk8
- oraclejdk7
- openjdk8

matrix:
fast_finish: true
include:
	- jdk: oraclejdk8
	  env: WITH_COVERALLS=true
	- jdk: oraclejdk7
	- jdk: openjdk6
